### ISSUE TITLE
Release Candidate Comments (Labor Investment)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#59]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Labor Investment**

GitHub location: https://github.com/chaoss/wg-value/blob/master/focus-areas/labor-investment/labor_investment.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by mbbroberg** [comment]
I'm working my way through metrics and providing some first impressions as a multi-time community lead in a large organization and open source contributor.

I have 2 different understandings and a few differing readings from this metric and will break out each. 

### Labor investment as a measurement of cost

My first understanding is based on the description and objectives. The framing of this metric states cost, specifically: 

> monetary investment of organizations (as evident in labor costs) to individual projects.

This sort of framing can be quite helpful if budget has already been secured, and an OSPO is looking to make a choice between investment in project X or Y. I'm in full support of that being a helpful way to normalize perceived cost and meaningfully allocate funding. 

What's not clear to me is if this metric is intended to help _justify budget_. In this case, the negative framing of cost before discussing potential value is not a measurement that align to business value. As a recommended practice, I find it important to advocate for a positive framing of the argument for funding before the math happens. Avoiding negative connotations or association with being a cost center instead of a business value is essential to landing funding in my experience. 

One other thought. Under objective: 

> As organizational engagement with open source projects becomes increasly important, it is important for organization to clearly understand their labor investment. 

Organizations I have worked with to consider investing in open source communities are happy to only estimate their costs as a sum of opex and capex spending (salaries of staff, participation in events, cost of tools). These estimations are always pit against some other opportunity to invest funds into whatever the perceived ROI is for open source contribution (often abstracted to attention, good will, top-of-funnel awareness and related. See https://github.com/chaoss/wg-value/issues/57). While estimates with decent assumptions are essential, accuracy is not likely when we think about pitching a new (and thus somewhat unknown) discussion on labor. I don't have a link handy, but I'm thinking of the work done around Scrum bug estimates and how those are relative values to that team, not generalize-able measurements. 

### Labor Investment as product management

Jumping to the end, there seems to be a differing objective. The visualization and filters recommended show what I would understand as product management prioritization ("based on estimated costs, where should we start working"). 

If this KPIs goal is to cover the value of working on different items in an open source project's backlog, this is a great ends and is well within my understanding what CHAOSS wants to measure. I even like it in the value group because it's about the providing an economic translation of community value. At the moment, this conclusion feels like a different goal than the presented objective. 

## Summary / TLDR 

I see three interpretations here and I'll frame them in relation to OSPOs to highlight it: 

1. Labor Investment as a means of evaluating OSPO priorities
2. Labor Investment as a budgeting justification for an OSPO priority
3. Labor Investment as an argument for the value of investing in OSPOs
4. Labor Investment as a way to explain product/program management priority

My take is if the goal is (1) or (3), it would be better done framed as ROI, where labor costs are a bullet in the estimate. Reframing to (2) would benefit from a positive connotation - something like "Prioritizing Investment" (labor is implied). If (4) is the goal, it would be clearer to talk about product or program prioirization and use some existing ROI model like this [lightweight one](https://uxdesign.cc/a-simple-way-to-model-roi-of-any-new-feature-a9828fbba27e) or [the RICE model](https://www.intercom.com/blog/rice-simple-prioritization-for-product-managers/). 

Arguments in favor as it stands: 

- Calculating any sense of return on investment isn't possible without a reasonable analysis of the financial cost of participate. 

Arguments in favor of revision: 

- Labor investment alone has the opposite effect of showing business value. 
- Label investment, to the best of my experience and understanding of peer organizations, is the denominator in an equation of value most often called _return on investment._

**Comment by GeorgLink** [comment]
@mbbroberg, during today's call, we tried to incorporate your different use cases of this metric into the objectives section so that others would benefit from your insights.

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
