### ISSUE TITLE
Release Candidate Comments (Social Currency Metric System (SCMS))

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-value#61]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Social Currency Metric System (SCMS)**

GitHub location: https://github.com/chaoss/wg-value/blob/master/focus-areas/ecosystem/social-currency-metric-system.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by mbbroberg** [comment]
I'm working my way through metrics and providing some first impressions as a community manager and open source contributor. 

For the introduction of SCMS, it's unclear to me who's using this metric and when. While I understand this is intended to be an aggregate or composite metric, who is using it and to measure what is unclear. I read:

> A central premise of this approach is that community members' interactions have an impact on the community.

And 

> After getting enough data to form a benchmark, take stock of where your community stands. What are its strengths and weaknesses? What actions can be taken to make the community healthier and more robust?

Is this saying in the first part that this measurement will allow a community member to assess how much of an influence (i.e. trust) they have on the outcomes of the community? Or is it a means of measuring sentiment of community members so that a community leader can improve upon the community's sense of trust? 

By the time I've reviewed all the examples at the bottom, I see this as an incredibly framework to benchmark and analyze community sentiment. This fits well into the goal of CHAOSS as a way to interpret community health (D&I and risk angles are evident), but I'm not clear on how it's a value metric as I conceptualize it. I say this because I can't imagine receiving further funding in a corporate environment based on doing this analysis, which is my personal metric of value. I can improve my community, but I could not justify its business value without further work outside of SCMS. 

My takeaways:  

- The intended usage of this is a still unclear to me. It'd be helpful to reframe the description to be an explanation to the intended user with a focus on derived value. If others feel similar, I'd be happy to help with a revision once I understand the context further. 
- I'm unclear on how this furthers the measured value of a community without additional analogies or calculations (ex. value of a positive review, cost of a negative review). Is my interpretation of Value aligned with the WG definition?

**Comment by germonprez** [comment]
Thanks @mbbroberg -- @GeorgLink do you have Samantha's GH id to ping her. She may have the best insight on these comments.

**Comment by GeorgLink** [comment]
I emailed Samantha with a link to @mbbroberg's comments. Thanks!

**Comment by mbbroberg** [comment]
Thanks all. Please let Samantha know I have a ton of respect for the science of this metric, and my question continues to hinge on the objective of the WGV's mission. 

> This fits well into the goal of CHAOSS as a way to interpret community health (D&I and risk angles are evident), but I'm not clear on how it's a value metric as I conceptualize it. I say this because I can't imagine receiving further funding in a corporate environment based on doing this analysis, which is my personal metric of value. I can improve my community, but I could not justify its business value without further work outside of SCMS.

☝️ I'd be curious for your feedback on this point @GeorgLink  / @germonprez when time permits, or we can table this for a discussion the next time I can make the meeting (AFK the rest of Jan starting next week). Thanks 🎉

**Comment by GeorgLink** [comment]
To @mbbroberg  points:

> * The intended usage of this is a still unclear to me. It'd be helpful to reframe the description to be an explanation to the intended user with a focus on derived value. If others feel similar, I'd be happy to help with a revision once I understand the context further.

To preserve the brevity of the metric, we removed the potential uses and examples. This would be great material for a blog post.

> * I'm unclear on how this furthers the measured value of a community without additional analogies or calculations (ex. value of a positive review, cost of a negative review). Is my interpretation of Value aligned with the WG definition?

I get the sense that you are looking for a dollar value but this metric is more about social currency, like reputation, trust, or transparency -- which are not monetary values.

During today's call, we revised the question and first sentence of the description to be more clear about what this metric is.

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
