### ISSUE TITLE
Multi Variable Correlation

### ISSUE THREAD

**Issue by andyl** [chaoss/wg-value#7]
With Value Metrics I expect stakeholders will tell us about Key Performance Indicators - things like 'project profit', 'cost per bug fix', 'time to hire a tier1 developer', etc.

At the same time, we'll have a big collection of metrics: things like 'average time to close an issue', 'contributor churn rate', 'blog post sentiment', and on and on.

I'd like to be able to show people which metrics most strongly correlate with business outcomes.

I'm not sure how to do this!  Maybe with traditional statistical techniques or maybe with some sort of ML / DataScience approach.

This is a call for discussion, and a call for VMG contributors.  If you are interested in Data Analytics this would be a really interesting project that could make a big impact.

**Comment by mpgjon** [comment]
I think KPI's in the Value chain overall are going to vary by stakeholder type; which, given the democratic tendencies in Open Source, I started calling "constituents" since stakeholder always makes me think of someone who is paying me to care what their opinions are ;) but I digress. 

I've started mapping out my thoughts here: https://docs.google.com/document/d/1mU5f4jXsB4p9WUboR22V97VybZTIL0vHnXPAREqMiUc/edit?usp=sharing and would love some feedback on if this model approach is useful or not. 

I like your mention of blog post sentiment, but wonder about implementation; and it might be simpler to use a social media sentiment service (of which there are many) as an enrichment data set. 

My broader point is that there are differing constituencies internal to the groups that care most above Value KPI's (that being mostly corporate entities sponsoring, contributing to, or using).

**Comment by germonprez** [comment]
Thanks @mpgjon this is great. It's a fantastic way to think about how the different working groups can be brought together. I really, really like this and think it's one of the first times the discussion in the project as really brought this lens forward.

**Comment by andyl** [comment]
@mpgjon had a quick look thru the google doc and ofc approve very much.  To me this looks like a market-segmentation exercise.  In my past experience we would drill into each segment methodically, and often times the gold is found in unexpected places!

**Comment by mbbroberg** [comment]
Hey all, this work is fantastic, though it's not quite the goal of our new direction for Value. Please see the [problem statement](https://github.com/chaoss/wg-value#problem-statement) and let me know if you'd like to participate. I'm closing in the meantime.
