### ISSUE TITLE
DevRel & OSPO: what metrics do you use to show community value?

### ISSUE THREAD

**Issue by mbbroberg** [chaoss/wg-value#79]
This is the start to a conversation with industry practitioners who identify with or relate to Developer Relations and Open Source Program Offices. I would like to get any and all references to DevRel and OSPO metrics of value from talks, books, and personal anecdotes. 

If you have a story to share, please do! 

Here's the hit list of resources I would like whoever is interested to help us go through the metrics mentioned in each of these resources:

- [ ] [The Business Value of Developer Relations](https://www.amazon.com/Business-Value-Developer-Relations-Communities/dp/1484237471)
- [ ] The [Art of Community](https://www.jonobacon.com/books/artofcommunity/) and other Jono resources
- [ ] The [TODO Group guide to measuring OSPOs](https://todogroup.org/guides/measuring/)
- [ ] ... more to come

## Add your story!

Comments welcome, no matter how specific to you and your environment they are. Please share ideas and, if you think it's a full fledged idea, open a PR with the proposed metric ([here's how](https://github.com/chaoss/wg-value#contributing)).

**Comment by samanthavenialogan** [comment]
Im biased XD, but I would be more than willing to help go through the data!

Call me for your free consultation! 307 274 5516

**Comment by GeorgLink** [comment]
Bias is good! Especially when you are aware of your bias. I see it as an acknowledged "Expert Opinion from a Specific Background". That's why we have a community review process so that different people can weigh in and we get the best of all opinions.

**Comment by samanthavenialogan** [comment]
That's fair,  Here's what I usually jump to: 

Books are hugely helpful in a lot of ways but honestly, I find that looking at other modes helps more? 
 I recommend going through DigitalMarketer's Online Community Management course by Suzi Nelson in addition to the aforementioned courses by Jono and Richard at Feverbee. 

Suzie's course has some awesome information about using often hard to implement theories like Levinger's relationship model, the sense of community survey, how marketing fits in with brand health, and some really practical ways to connect community value to brand benefit.  It's for brand communities, but they translate really really well. 

**Books I recommend:**
> Buzzing Communities: How to Build Bigger, Better, and More Active Online Communities
He also published an awesome book called "indispensable communities" that's worth a read.  

> * The [Art of Community](https://www.jonobacon.com/books/artofcommunity/) and other Jono resources
Jono Bacon's "the art of community" is also followed up with his most recent book People-powered so that's worth a look.  

I also recommend Tara Hunt's "[the Whuffie Factor"](https://www.amazon.com/Whuffie-Factor-Social-Networks-Business/dp/0307409503) based off of an awesome fictional sci-fi called down and out in the magic kingdom.  

I think It's really important as well if you're a community manager, to understand how virtual teams work on a smaller level, so I recommend the book, "virtual teams that work".  It's actually available on the[ internet as a PDF here](http://www.communicationcache.com/uploads/1/0/8/8/10887248/virtual_teams_that_work_creating_conditions_for_virtual_team_effectiveness.pdf). 

The numbers are always important but they haven't really "changed" much.  Instead of scouring for KPIs that you "should" be looking for I find it's better to get the theory behind what merics you can create yourself.  

As far that goes I usually bend on the 5-pillars of measurement marketing as taught by Chris Mercer's content on data analytics at measurementmarketing.io. 

I find that when you understand how to implement your average community member's story, you discover what KPIs tell you the most important plot points.  Then, as I'm sure you know, I use anthropological content to fill in, confirm, and reiterate that story.    

Some good social science and communications sources that are worth using for this include: 
1. [Ethnography in virtual worlds: A handbook of method](https://press.princeton.edu/books/hardcover/9780691149509/ethnography-and-virtual-worlds)
2. [Salsa Dancing in to the Social Sciences](https://www.amazon.com/Salsa-Dancing-into-Social-Sciences-dp-0674031571/dp/0674031571/ref=mt_hardcover?_encoding=UTF8&me=&qid=)
3. [Twitter and Tear Gas](https://www.audible.com/pd/Twitter-and-Tear-Gas-Audiobook/B06XS39NNS?ds_rl=1262685&ds_rl=1263561&ds_rl=1260658&source_code=GO1GB907OSH060513&gclid=Cj0KCQjws_r0BRCwARIsAMxfDRiBeVdLmw0FNSmt-YRFdr-hRe_vRhC7-aLnOzzwU0eDUiONrXXN1w8aAkSSEALw_wcB&gclsrc=aw.ds)
4. [Communities of Play](https://mitpress.mit.edu/books/communities-play)

**Comment by nuritzi** [comment]
I came across this resource from Oracle as a way to measure the Return on Investment (ROI) of online communities: [Oracle's Best Practices Guide on Measuring Community ROI](http://www.oracle.com/us/media1/bp-meas-roi-online-com-wp-1588494.pdf). 

I like how it does try to tie in monetary value and has formulas you can use. I recognize that there are things you can't measure in monetary value, but thought I'd share this resource anyway as something for us to consider :)

**Comment by GeorgLink** [comment]
Thanks @nuritzi, the community ROI guide is very extensive and a quite interesting read. Thanks for sharing!

**Comment by ElizabethN** [comment]
Going to close this, as it doesn't appear to have any action needed. Thanks for the resources everyone!
